apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
type: Opaque
stringData:
  # PostgreSQL
  DB_URL: "jdbc:postgresql://postgresql-service:5432/payment_service_db"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "123456"
  
  # MongoDB
  MONGODB_URI: "mongodb://mongodb:27017/payment_service_db"
  MONGODB_USERNAME: "root"
  MONGODB_PASSWORD: "123456"
  
  # External services API keys
  USER_SERVICE_API_KEY: "internal-auth-key-12345"
  ORDER_SERVICE_API_KEY: "internal-auth-key-12345"